                                        # SETTINGS!

# Title of the website
title: "Virus Epidemiology and Control Group"

# The slogan describes the website and is used on homepage in <title> and other important places
slogan: "Virus Epidemiology and Control"

# The description is used on homepage and in the footer to quickly describe the website. Use a maximum of 150 characters for SEO-purposes.
description: "We conduct research into population dynamics of viral pathogens" 

# Main author of the website
# See > authors.yml
author: virec-group

# This URL is the main address for absolute links. Don't include a slash at the end.
url: ''
baseurl: ''

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.

# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)

urlimg: 'http://virec-group.org/images/'

# Logo size is 600x80 pixels
logo: "logo.png"

# Pagination
gems: [jekyll-paginate]
paginate: 5                      # Paginates all X entries
paginate_path: "blog/page:num"   # Pagination path › Important for blog page in /blog/ to work


# Theme works best with Kramdown (using the table of contents function)
markdown: kramdown
permalink: /:categories/:title/
highlight: rouge
excerpt_separator: "<!--more-->"
include: ['.htaccess']
# Exclude these files from the production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - INSTALL.md


# The language setting is used in /includes/header.html for html-settings
language: "en"


# Used › default.html front-matter and compress.html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]

# Default Settings
defaults:
  -
    scope:
      path: "" 				# an empty string here means all files in the project
      type: "pages"
    values:
      show_meta: false 	    # Hide metadata for all pages
      sidebar:  left  		# Possible values › left, right › by default there will be no sidebar
      comments: false
      author: VEClab        # Default author for pages
  -
    scope:
      path: ""
      type: "posts"
    values:
      show_meta: true   # Show metadata for all posts
     #sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: VecLab     # Default author for posts

#  Navigation
#  Open _data/navigation.yml to adjust the left and right topbar navigation

#   Verify Website to Webmaster Tools

      #google_author:             ""
      #google_site_verification:  ""
      #bing_webmastertools_id:    ""
# alexa_verify_id:         ""


#    Favicon-Crap: Favicons, Chrome, Android & Apple Touch Buttons
#    More information » https://mathiasbynens.be/notes/touch-icons

favicon-32x32:                          "favicon-32x32.png"
touch-icon-192x192:                     "touch-icon-192x192.png"
apple-touch-icon-180x180-precomposed:   "apple-touch-icon-180x180-precomposed.png"
apple-touch-icon-152x152-precomposed:   "apple-touch-icon-152x152-precomposed.png"
apple-touch-icon-144x144-precomposed:   "apple-touch-icon-144x144-precomposed.png"
apple-touch-icon-120x120-precomposed:   "apple-touch-icon-120x120-precomposed.png"
apple-touch-icon-114x114-precomposed:   "apple-touch-icon-114x114-precomposed.png"
apple-touch-icon-76x76-precomposed:     "apple-touch-icon-76x76-precomposed.png"
apple-touch-icon-72x72-precomposed:     "apple-touch-icon-72x72-precomposed.png"
apple-touch-icon-precomposed:           "apple-touch-icon-precomposed.png"
msapplication_tileimage:                "msapplication_tileimage.png"               # Size 144x144
msapplication_tilecolor:                "#fabb00"


# Social media
#  Open _data/socialmedia.yml to adjust the left and right topbar navigation

# Disqus
# used in _includes/comments
#disqus_shortname: virec-group
   
#   More › http://sass-lang.com/
#   More › http://jekyllrb.com/docs/assets/#sassscss
sass:
    sass_dir: _sass
    style: :compressed


# Analytics
# used in _includes/footer_scripts

google_analytics_tracking_id: UA-77331498-1
